### ISSUE TITLE
Segmented point cloud only labelled with 0s

### ISSUE THREAD

**Issue by julien-arch** [MarkusEich/cpf_segmentation#1]
When running ./segmentation_test test_data/dining_room_0001a_redux.pcd -o,
the points in the resulting file are all labelled with 0 as 4th coordinate, e.g.
-1.8683062 0.56312746 0.78754455 0
-1.8874744 0.52467334 0.79544008 0
when the console mentions 8 labels: Creating graph with 13385 nodes and 8 labels

**Comment by trungtpham** [comment]
We have fixed the bug. Could you please try again? We have added a live demo using kinect as well.

Cheers,
Trung
